-- Push notifications (Web Push).
-- Flow: a row is inserted → trigger → private.push_notify → pg_net POST to the `push` Edge Function
-- (authenticated with a shared secret kept in Vault) → Web Push to the recipients' registered devices.
-- Secrets (hook secret, VAPID keys) live only in Vault: the hook secret is generated here, the VAPID key pair
-- is generated by the Edge Function on first use.

create extension if not exists pg_net with schema extensions;

select vault.create_secret(
  encode(extensions.gen_random_bytes(24), 'hex'),
  'push_hook_secret',
  'Shared secret between database triggers and the push Edge Function'
);

-- ─── Subscriptions (one per device/browser) ─────────────────

create table public.push_subscriptions (
  id          uuid primary key default gen_random_uuid(),
  profile_id  uuid not null references public.profiles (id) on delete cascade,
  endpoint    text not null unique,
  p256dh      text not null,
  auth        text not null,
  user_agent  text not null default '',
  created_at  timestamptz not null default now()
);
create index on public.push_subscriptions (profile_id);

alter table public.push_subscriptions enable row level security;
create policy "own subscriptions" on public.push_subscriptions
  for all to authenticated
  using (profile_id = (select auth.uid()))
  with check (profile_id = (select auth.uid()));

-- A device endpoint may previously belong to the other person (shared phone): take it over.
create function public.register_push_subscription(p_endpoint text, p_p256dh text, p_auth text, p_user_agent text default '')
returns void language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  delete from public.push_subscriptions where endpoint = p_endpoint;
  insert into public.push_subscriptions (profile_id, endpoint, p256dh, auth, user_agent)
  values (auth.uid(), p_endpoint, p_p256dh, p_auth, left(coalesce(p_user_agent, ''), 300));
end $$;

create function public.unregister_push_subscription(p_endpoint text) returns void
language sql security definer set search_path = '' as $$
  delete from public.push_subscriptions where endpoint = p_endpoint and profile_id = auth.uid();
$$;

revoke execute on function public.register_push_subscription(text, text, text, text),
  public.unregister_push_subscription(text) from public, anon;
grant execute on function public.register_push_subscription(text, text, text, text),
  public.unregister_push_subscription(text) to authenticated;

-- ─── Config for the Edge Function (service role only) ───────

create function public.push_config() returns jsonb
language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'hook_secret',   (select decrypted_secret from vault.decrypted_secrets where name = 'push_hook_secret'),
    'vapid_public',  (select decrypted_secret from vault.decrypted_secrets where name = 'push_vapid_public'),
    'vapid_private', (select decrypted_secret from vault.decrypted_secrets where name = 'push_vapid_private')
  )
$$;

create function public.push_store_vapid(p_public text, p_private text) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not exists (select 1 from vault.secrets where name = 'push_vapid_public') then
    perform vault.create_secret(p_public, 'push_vapid_public', 'Web Push VAPID public key');
    perform vault.create_secret(p_private, 'push_vapid_private', 'Web Push VAPID private key');
  end if;
end $$;

revoke execute on function public.push_config(), public.push_store_vapid(text, text) from public, anon, authenticated;
grant execute on function public.push_config(), public.push_store_vapid(text, text) to service_role;

-- ─── Sending ────────────────────────────────────────────────

-- Recipients: explicit list, or every household member except the actor. Never fails the calling statement.
create function private.push_notify(
  p_household uuid, p_actor uuid, p_recipients uuid[], p_title text, p_body text, p_url text
) returns void language plpgsql security definer set search_path = '' as $$
declare
  v_recipients uuid[] := p_recipients;
  v_secret text;
begin
  if v_recipients is null then
    select array_agg(id) into v_recipients from public.profiles
    where household_id = p_household and (p_actor is null or id <> p_actor);
  end if;
  if v_recipients is null
     or not exists (select 1 from public.push_subscriptions where profile_id = any (v_recipients)) then
    return;
  end if;
  select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'push_hook_secret';
  perform net.http_post(
    url := 'https://ksvhejfppcdspxqaticc.supabase.co/functions/v1/push',
    body := jsonb_build_object('recipients', v_recipients, 'title', p_title, 'body', p_body, 'url', p_url),
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-push-secret', v_secret)
  );
exception when others then
  raise warning 'push_notify failed: %', sqlerrm;
end $$;

create function private.euros(p_cents bigint) returns text
language sql immutable set search_path = '' as $$
  select '€' || to_char(p_cents / 100.0, 'FM999G999G990D00')
$$;

create function private.display_name(p_profile uuid) returns text
language sql stable security definer set search_path = '' as $$
  select coalesce(nullif(display_name, ''), 'Someone') from public.profiles where id = p_profile
$$;

-- New shared entry → the other person. Generated by the daily job (no user) → both.
create function private.push_on_entry() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  v_cat record;
  v_what text;
  v_actor uuid := auth.uid();
begin
  if new.split_type = 'personal' then return null; end if;
  select name, emoji into v_cat from public.categories where id = new.category_id;
  v_what := coalesce(nullif(new.note, ''), v_cat.name, 'Expense');
  if v_actor is null then
    perform private.push_notify(new.household_id, null, null,
      '🔁 ' || v_what || ' · ' || private.euros(new.amount_cents),
      'Recurring ' || case when new.kind = 'refund' then 'refund' else 'expense' end || ' added',
      '/entry/' || new.id);
  else
    perform private.push_notify(new.household_id, v_actor, null,
      coalesce(v_cat.emoji || ' ', '') || private.display_name(v_actor)
        || case when new.kind = 'refund' then ' received ' else ' added ' end || private.euros(new.amount_cents),
      v_what,
      '/entry/' || new.id);
  end if;
  return null;
end $$;

create trigger push_on_entry after insert on public.entries
  for each row execute function private.push_on_entry();

-- New reminder → whoever can see the template (personal → its owner only).
create function private.push_on_pending() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  t public.recurring_templates;
begin
  select * into t from public.recurring_templates where id = new.template_id;
  perform private.push_notify(new.household_id, null,
    case when t.split_type = 'personal' then array[t.payer_id] else null end,
    '🔔 ' || coalesce(nullif(t.note, ''), 'Recurring expense') || ' is due',
    'Confirm the amount (last ' || private.euros(new.suggested_amount_cents) || ')',
    '/add?pending=' || new.id);
  return null;
end $$;

create trigger push_on_pending after insert on public.pending_recurring
  for each row execute function private.push_on_pending();

create function private.push_on_settlement() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  perform private.push_notify(new.household_id, auth.uid(), null,
    '⇄ ' || private.display_name(new.from_id) || ' → ' || private.display_name(new.to_id) || ': '
      || private.euros(new.amount_cents),
    'Transfer recorded by ' || private.display_name(coalesce(auth.uid(), new.created_by)),
    '/balance');
  return null;
end $$;

create trigger push_on_settlement after insert on public.settlements
  for each row execute function private.push_on_settlement();

create function private.push_on_period() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  perform private.push_notify(new.household_id, auth.uid(), null,
    '🔒 ' || trim(to_char(new.month, 'FMMonth YYYY')) || ' closed',
    'Closed by ' || private.display_name(coalesce(auth.uid(), new.closed_by)) || '. Check the month summary.',
    '/balance/' || to_char(new.month, 'YYYY-MM'));
  return null;
end $$;

create trigger push_on_period after insert on public.periods
  for each row execute function private.push_on_period();

-- Test from Settings: notify only the caller's own devices.
create function public.send_test_push() returns void
language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  perform private.push_notify(null, null, array[auth.uid()], '🔔 Freecount', 'Notifications work on this device.', '/');
end $$;

revoke execute on function public.send_test_push() from public, anon;
grant execute on function public.send_test_push() to authenticated;

revoke execute on function
  private.push_notify(uuid, uuid, uuid[], text, text, text), private.euros(bigint), private.display_name(uuid),
  private.push_on_entry(), private.push_on_pending(), private.push_on_settlement(), private.push_on_period()
  from public, anon, authenticated;
